version: '3'
services:
  web:
    build: .
    command: rails s -b 0.0.0.0
    ports:
      - 80:3000
    volumes:
      - .:/nutrilife
    env_file:
      - .env.docker
    links:
      - db
  db:
    image: postgres
    ports:
      - 0:5432
    volumes:
      - nutrilife-data:/var/lib/postgresql/data
    env_file:
      - .env.docker
volumes:
  nutrilife-data:


